language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t shivanandchikkalli/docker-react .


script:
  - docker run -e CI=true shivanandchikkalli/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-ap-south-1-608972471936"
  bucker_path: "docker"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

