sudo: required
services:
  - docker


before_install:
  - docker build -t github-frontend -f Dockerfile.dev .


#script:
#  - docker run github-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-1-608972471936"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"